version: "2.4"
networks:
  demo-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.96.0/20
services:
  database:
    image: postgres:latest
    networks:
      demo-network:
        ipv4_address: 192.168.96.2
        aliases:
          - postgreSQL
    hostname: postgreSQL
    container_name: postgreSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "demo"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c "max_prepared_transactions=100"
  database2:
    image: postgres:latest
    networks:
      demo-network:
        ipv4_address: 192.168.96.30
        aliases:
          - postgreSQL2
    hostname: postgreSQL2
    container_name: postgreSQL2
    ports:
      - "8432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "demo2"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c "max_prepared_transactions=100"
  activemq:
    image: rmohr/activemq
    networks:
      demo-network:
        ipv4_address: 192.168.96.20
        aliases:
          - activemq
    hostname: activemq
    container_name: activemq
    user: root
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./active-mq/conf/:/opt/activemq/conf
      - ./active-mq/data/:/opt/activemq/data
  adminer:
    image: adminer
    networks:
      demo-network:
        ipv4_address: 192.168.96.10
        aliases:
          - adminer
    depends_on:
      database:
        condition: service_healthy
    hostname: adminer
    container_name: adminer
    ports:
      - 8081:8080
  demo-eureka:
    image: demo-eureka:0.0.1-SNAPSHOT
    networks:
      demo-network:
        ipv4_address: 192.168.96.27
        aliases:
          - demo-eureka
    depends_on:
      database:
        condition: service_healthy
    hostname: demo-eureka
    container_name: demo-eureka
    ports:
      - "8070:8070"
  demo-gateway:
    image: demo-gateway:0.0.1-SNAPSHOT
    networks:
      demo-network:
        ipv4_address: 192.168.96.35
        aliases:
          - demo-gateway
    depends_on:
      - demo-eureka
    hostname: demo-gateway
    container_name: demo-gateway
    ports:
      - "8072:8072"
  demo-api:
    image: demo-api:0.0.1-SNAPSHOT
    networks:
      demo-network:
        ipv4_address: 192.168.96.3
        aliases:
          - demo-api
    environment:
      DATABASESERVER_PORT: "5432"
    depends_on:
      - database
      - demo-eureka
      - demo-gateway
    hostname: demo-api
    container_name: demo-api
    ports:
      - "8080:8080"
  demo-api-2:
    image: demo-api:0.0.1-SNAPSHOT
    networks:
      demo-network:
        ipv4_address: 192.168.96.36
        aliases:
          - demo-api-2
    environment:
      DATABASESERVER_PORT: "5432"
    depends_on:
      - database
      - demo-eureka
      - demo-gateway
    hostname: demo-api
    container_name: demo-api-2
    ports:
      - "8090:8080"
  demo-job:
    image: demo-job:0.0.1-SNAPSHOT
    networks:
      demo-network:
        ipv4_address: 192.168.96.5
        aliases:
          - demo-job
    environment:
      DATABASESERVER_PORT: "5432"
    depends_on:
      - database
      - demo-eureka
      - demo-gateway
    hostname: demo-job
    container_name: demo-job
    ports:
      - "8085:8080"
  demo-xa:
    image: demo-xa:0.0.1-SNAPSHOT
    networks:
      demo-network:
        ipv4_address: 192.168.96.7
        aliases:
          - demo-xa
    environment:
      DATABASESERVER_PORT: "5432"
    depends_on:
      database2:
        condition: service_healthy
    hostname: demo-xa
    container_name: demo-xa
    ports:
      - "8086:8080"

