spring:
  application:
    name: demo-xa
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://postgresql2:5432/demo2
    xa:
      data-source-class-name: org.postgresql.xa.PGXADataSource
    username: postgres
    password: postgres
    initialization-mode: always
  jta:
    atomikos:
      connectionfactory:
        ignore-session-transacted-flag: false
        unique-resource-name: xa.amq
        min-pool-size: 10
        max-pool-size: 20
      datasource:
        unique-resource-name: xa.db
        min-pool-size: 10
        max-pool-size: 20
        test-query: "select 1"
      properties:
        default-jta-timeout: 300000
  jmx:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://demo-eureka:8070/eureka/
logging:
  level:
    com.atomikos.datasource.xa.XAResourceTransaction: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
hawtio:
  authenticationEnabled: false