apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-xa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xa
  template:
    metadata:
      name: demo-xa-deployment
      labels:
        app: xa
    spec:
      containers:
        - name: demo-xa
          #image: 172.19.0.2:5000/demo-xa:0.0.1-SNAPSHOT
          image: localhost:5000/demo-xa:0.0.1-SNAPSHOT
          env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://eurekaserver:8070/eureka/
