apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgreSQL
  template:
    metadata:
      name: postgres-deployment
      labels:
        app: postgreSQL
    spec:
      containers:
        - env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://eurekaserver:8070/eureka/
          image: 172.19.0.2:5000/postgres:0.0.1-SNAPSHOT
          name: postgres
