apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: demo-api-deployment
      labels:
        app: api
    spec:
      containers:
        - name: demo-api
          #image: 172.19.0.2:5000/demo-api:0.0.1-SNAPSHOT
          image: localhost:5000/demo-api:0.0.1-SNAPSHOT
          env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://eurekaserver:8070/eureka/
