apiVersion: v1
kind: Service
metadata:
  labels:
    fr.dsirc.service: postgresql
  name: postgresql
spec:
  type: NodePort
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      nodePort: 31623
  selector:
    fr.dsirc.service: postgresql

