apiVersion: v1
kind: Service
metadata:
  name: demo-api
  labels:
    fr.dsirc.service: demo-api
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30223
  selector:
    fr.dsirc.service: demo-api

