apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-job
  labels:
    fr.dsirc.service: demo-job
spec:
  replicas: 1
  selector:
    matchLabels:
      fr.dsirc.service: demo-job
  template:
    metadata:
      name: demo-job
      labels:
        fr.dsirc.service: demo-job
    spec:
      containers:
        - name: demo-job
          image: localhost:5000/demo-job:0.0.1-SNAPSHOT
          env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://demo-eureka:8070/eureka/
