apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    fr.dsirc.service: activemq
spec:
  type: NodePort
  ports:
    - name: http
      port: 8161
      targetPort: 8161
      nodePort: 30823
  selector:
    fr.dsirc.service: activemq
