apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8161
      targetPort: 8161
      nodePort: 30823
  selector:
    app: active-mq