apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-eureka
  labels:
    fr.dsirc.service: demo-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
     fr.dsirc.service: demo-eureka
  template:
    metadata:
      name: demo-eureka
      labels:
        fr.dsirc.service: demo-eureka
    spec:
      containers:
        - name: demo-eureka
          image: localhost:5000/demo-eureka:0.0.1-SNAPSHOT
