apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  labels:
    fr.dsirc.service: adminer
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30123
  selector:
    fr.dsirc.service: adminer

