apiVersion: v1
kind: Service
metadata:
  name: demo-xa
  labels:
    fr.dsirc.service: demo-xa
spec:
  type: NodePort
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      nodePort: 31723
  selector:
    fr.dsirc.service: demo-xa

