apiVersion: v1
kind: Service
metadata:
  name: demo-gatewy
  labels:
    fr.dsirc.service: demo-gateway
spec:
  type: NodePort
  ports:
    - name: http
      port: 8072
      targetPort: 8072
      nodePort: 30433
  selector:
    fr.dsirc.service: demo-gateway

