apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        name: spring-cloud-gateway-deployment
        app: gateway
    spec:
      containers:
        - name: demo-gateway
          image: spring-cloud-eureka-deployment/demo-gateway:0.0.1-SNAPSHOT
          env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://eurekaserver:8070/eureka/
