apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fr.dsirc.service: postgresql
  name: postgresql
spec:
  replicas: 2
  selector:
    matchLabels:
      fr.dsirc.service: postgresql
  template:
    metadata:
      name: postgres-deployment
      labels:
        fr.dsirc.service: postgresql
    spec:
      hostname: postgresql
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://eurekaserver:8070/eureka/
          envFrom:
            - configMapRef:
                name: postgresql
