apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: active-mq
  template:
    metadata:
      name: activemq-deployment
      labels:
        app: active-mq
    spec:
      containers:
        - image: rmohr/activemq:latest
          name: activemq