apiVersion: v1
kind: Service
metadata:
  name: demo-xa-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8085
      targetPort: 8086
      nodePort: 31723
  selector:
    name: demo-xa
    category: business

