apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-gateway
  labels:
    fr.dsirc.service: demo-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      fr.dsirc.service: demo-gateway
  template:
    metadata:
      labels:
        name: demo-gateway
        fr.dsirc.service: demo-gateway
    spec:
      containers:
        - name: demo-gateway
          image: localhost:5000/demo-gateway:0.0.1-SNAPSHOT
          env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://demo-eureka:8070/eureka/
