apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  labels:
    fr.dsirc.service: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      fr.dsirc.service: activemq
  template:
    metadata:
      name: activemq
      labels:
        fr.dsirc.service: activemq
    spec:
      containers:
        - image: rmohr/activemq:latest
          name: activemq