apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-job-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      name: demo-job-deployment
      labels:
        app: job
    spec:
      containers:
        - name: demo-job
          image: 172.19.0.2:5000/demo-job:0.0.1-SNAPSHOT
          env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://eurekaserver:8070/eureka/
