apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  labels:
    fr.dsirc.service: demo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      fr.dsirc.service: demo-api
  template:
    metadata:
      name: demo-api-deployment
      labels:
        fr.dsirc.service: demo-api
    spec:
      containers:
        - name: demo-api
          image: localhost:5000/demo-api:0.0.1-SNAPSHOT
          env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://demo-eureka:8070/eureka/
