apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      nodePort: 31623
  selector:
    app: postgres
    category: infra
