apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-eureka-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8070
      targetPort: 8070
      nodePort: 30333
  selector:
    app: eureka
