apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      category: infra
  template:
    metadata:
      name: demo-eureka
      labels:
        category: infra
    spec:
      containers:
      - image: 459436678662.dkr.ecr.eu-west-3.amazonaws.com/demo-eureka:0.0.1-SNAPSHOT
        name: demo-eureka
