apiVersion: v1
kind: Service
metadata:
  name: demo-job
  labels:
    fr.dsirc.service: demo-job
spec:
  type: NodePort
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      nodePort: 30523
  selector:
    fr.dsirc.service: demo-job
