apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    fr.dsirc.service: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      fr.dsirc.service: adminer
  template:
    metadata:
      name: adminer
      labels:
        fr.dsirc.service: adminer
    spec:
      containers:
        - image: adminer:latest
          name: adminer