apiVersion: v1
kind: Service
metadata:
  name: demo-eureka
  labels:
    fr.dsirc.service: demo-eureka
spec:
  type: NodePort
  ports:
    - name: http
      port: 8070
      targetPort: 8070
      nodePort: 30333
  selector:
    fr.dsirc.service: demo-eureka
