apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer-ui
  template:
    metadata:
      name: adminer-deployment
      labels:
        app: adminer-ui
    spec:
      containers:
        - image: adminer:latest
          name: adminer