apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      name: spring-cloud-eureka-deployment
      labels:
        app: eureka
    spec:
      containers:
      - image: spring-cloud-eureka-deployment/demo-eureka:0.0.1-SNAPSHOT
        name: demo-eureka
