apiVersion: v1
kind: Service
metadata:
  name: demo-api-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30223
  selector:
    app: demo-api
    category: business

