apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      category: infra
  template:
    metadata:
      labels:
        name: spring-cloud-gateway-deployment
        category: infra
    spec:
      containers:
        - env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://eurekaserver:8070/eureka/
          image: 459436678662.dkr.ecr.eu-west-3.amazonaws.com/demo-gateway:0.0.1-SNAPSHOT
          name: "demo-gateway"
