apiVersion: v1
kind: Service
metadata:
  annotations:
    image.name: demo-eureka:0.0.1-SNAPSHOT
  creationTimestamp: null
  labels:
    category: infra
  name: "spring-cloud-eureka-service"
spec:
  type: NodePort
  ports:
    - name: "8070"
      port: 8070
      targetPort: 8070
      nodePort: 31100
  selector:
    category: infra
status:
  loadBalancer: {}
