apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      category: business
  template:
    metadata:
      name: demo-api-deployment
      labels:
        category: business
    spec:
      containers:
        - env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://eurekaserver:8070/eureka/
          image: 459436678662.dkr.ecr.eu-west-3.amazonaws.com/demo-api:0.0.1-SNAPSHOT
          name: "demo-api"
