apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      category: infra
  template:
    metadata:
      name: activemq-deployment
      labels:
        category: infra
    spec:
      containers:
        - image: 459436678662.dkr.ecr.eu-west-3.amazonaws.com/rmohr/activemq:latest
          name: "activemq"