apiVersion: apps/v1
kind: Deployment
metadata:
  name: "postgres-deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      category: infra
  template:
    metadata:
      name: postgres
      labels:
        category: infra
    spec:
      containers:
        - env:
            - name: EUREKASERVER_PORT
              value: "8070"
            - name: EUREKASERVER_URI
              value: http://eurekaserver:8070/eureka/
          image: 459436678662.dkr.ecr.eu-west-3.amazonaws.com/postgres:0.0.1-SNAPSHOT
          name: "postgres"
