version: "2.4"
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/20
services:
  registry:
    image: registry:latest
    networks:
      net:
        ipv4_address: 172.19.0.2
        aliases:
          - registry
    hostname: registry
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry-config/config.yml:/etc/docker/registry/config.yml
  registry-ui:
    image: joxit/docker-registry-ui:latest
    networks:
      net:
        ipv4_address: 172.19.0.3
        aliases:
          - registry-ui
    environment:
      REGISTRY_TITLE: AGIRC-ARRCO private docker registry
      REGISTRY_URL: http://172.19.0.2:5000
      DELETE_IMAGES: "true"
      SINGLE_REGISTRY: "true"
      NGINX_PROXY_PASS_URL: http://172.19.0.2:5000
    depends_on:
      - registry
    hostname: registry-ui
    container_name: registry-ui
    ports:
      - "80:80"