version: "2.4"
services:
  registry:
    image: registry:latest
    hostname: registry
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry-config/config.yml:/etc/docker/registry/config.yml
  registry-ui:
    image: joxit/docker-registry-ui:latest
    environment:
      REGISTRY_TITLE: AGIRC-ARRCO private docker registry
      REGISTRY_URL: http://localhost:5000
      DELETE_IMAGES: "true"
      SINGLE_REGISTRY: "true"
      NGINX_PROXY_PASS_URL: http://registry:5000
    depends_on:
      - registry
    hostname: registry-ui
    container_name: registry-ui
    ports:
      - "80:80"